# Site Settings
title: CV Romain PREZIOSI
email: rpreziosi00@gmail.com
description: Some text about your blog.
baseurl: "/jekflix-template" # the subpath of your site, e.g. /blog
url: "https://www.rossener.com" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: PREZIOSI Romain
user_description: Some text about you.
disqus_username: disqus_username

# Social Media
github_username: PreziosiR
linkedin_username: romain-preziosi-73aa10a4

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Accueil
    url: /
  - title: A propos
    url: /about/
  - title: Contact
    url: /contact/


# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
